language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - CAKE_VERSION=2.5.4
  - CAKE_VERSION=2.5.5

before_script:
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../cakephp-bootstrap3-helpers plugins/Bs3Helpers
  - chmod -R 777 ../cakephp/app/tmp
  - composer global require 'phpunit/phpunit=3.7.33'
  - ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ../cakephp/vendors/PHPUnit
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php

script:
  - ./lib/Cake/Console/cake test Bs3Helpers AllTests --stderr

notifications:
  email: false
